=== PavlidisLab/Gemma/gemma-core/src/test/resources/ehcache.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.7">

    <xs:element name="ehcache">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="diskStore"/>
                <xs:element minOccurs="0" ref="transactionManagerLookup"/>
                <xs:element minOccurs="0" ref="cacheManagerEventListenerFactory"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="cacheManagerPeerProviderFactory"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="cacheManagerPeerListenerFactory"/>
                <xs:element minOccurs="0" ref="terracottaConfig"/>
                <xs:element minOccurs="0" ref="defaultCache"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="cache"/>
            </xs:sequence>
            <xs:attribute name="name"/>
            <xs:attribute default="true" name="updateCheck" type="xs:boolean"/>
            <xs:attribute default="autodetect" name="monitoring" type="monitoringType"/>
            <xs:attribute default="true" name="dynamicConfig" type="xs:boolean"/>
            <xs:attribute default="15" name="defaultTransactionTimeoutInSeconds" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="diskStore">
        <xs:complexType>
            <xs:attribute name="path"/>
        </xs:complexType>
    </xs:element>
     <xs:element name="transactionManagerLookup">
        <xs:complexType>
            <xs:attribute name="class" use="required"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cacheManagerEventListenerFactory">
        <xs:complexType>
            <xs:attribute name="class" use="required"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cacheManagerPeerProviderFactory">
        <xs:complexType>
            <xs:attribute name="class" use="required"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cacheManagerPeerListenerFactory">
        <xs:complexType>
            <xs:attribute name="class" use="required"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="terracottaConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="tc-config">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:any maxOccurs="unbounded" minOccurs="0" processContents="skip"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute default="localhost:9510" name="url"/>
            <xs:attribute name="rejoin" type="xs:boolean" default="false"/>
        </xs:complexType>
    </xs:element>
    <!-- add clone support for addition of cacheExceptionHandler. Important! -->
    <xs:element name="defaultCache">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="cacheEventListenerFactory"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="cacheExtensionFactory"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="cacheLoaderFactory"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="cacheDecoratorFactory"/>
                <xs:element minOccurs="0" ref="bootstrapCacheLoaderFactory"/>
                <xs:element minOccurs="0" ref="cacheExceptionHandlerFactory"/>
                <xs:element minOccurs="0" ref="terracotta"/>
                <xs:element minOccurs="0" ref="cacheWriter"/>
                <xs:element minOccurs="0" ref="copyStrategy"/>
                <xs:element minOccurs="0" ref="elementValueComparator"/>
            </xs:sequence>
            <xs:attribute name="diskExpiryThreadIntervalSeconds" type="xs:integer"/>
            <xs:attribute name="diskSpoolBufferSizeMB" type="xs:integer"/>
            <xs:attribute name="diskPersistent" type="xs:boolean"/>
            <xs:attribute name="diskAccessStripes" type="xs:integer" default="1"/>
            <xs:attribute name="eternal" type="xs:boolean" use="required"/>
            <xs:attribute name="maxElementsInMemory" type="xs:integer" use="required"/>
            <xs:attribute name="clearOnFlush" type="xs:boolean"/>
            <xs:attribute name="memoryStoreEvictionPolicy" type="xs:string"/>
            <xs:attribute name="overflowToDisk" type="xs:boolean" use="required"/>
            <xs:attribute name="timeToIdleSeconds" type="xs:integer"/>
            <xs:attribute name="timeToLiveSeconds" type="xs:integer"/>
            <xs:attribute name="maxElementsOnDisk" type="xs:integer"/>
            <xs:attribute name="transactionalMode" type="transactionalMode" default="off"/>
            <xs:attribute name="statistics" type="xs:boolean" default="false"/>
            <xs:attribute name="copyOnRead" type="xs:boolean" default="false"/>
            <xs:attribute name="copyOnWrite" type="xs:boolean" default="false"/>
            <xs:attribute name="cacheLoaderTimeoutMillis" type="xs:integer" default="0"/>
            <xs:attribute name="overflowToOffHeap" type="xs:boolean" default="false"/>
            <xs:attribute name="maxMemoryOffHeap" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cache">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="cacheEventListenerFactory"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="cacheExtensionFactory"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="cacheLoaderFactory"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="cacheDecoratorFactory"/>
                <xs:element minOccurs="0" ref="bootstrapCacheLoaderFactory"/>
                <xs:element minOccurs="0" ref="cacheExceptionHandlerFactory"/>
                <xs:element minOccurs="0" ref="terracotta"/>
                <xs:element minOccurs="0" ref="cacheWriter"/>
                <xs:element minOccurs="0" ref="copyStrategy"/>
                <xs:element minOccurs="0" ref="searchable"/>
                <xs:element minOccurs="0" ref="elementValueComparator"/>
            </xs:sequence>
            <xs:attribute name="diskExpiryThreadIntervalSeconds" type="xs:integer"/>
            <xs:attribute name="diskSpoolBufferSizeMB" type="xs:integer"/>
            <xs:attribute name="diskPersistent" type="xs:boolean"/>
            <xs:attribute name="diskAccessStripes" type="xs:integer" default="1"/>
            <xs:attribute name="eternal" type="xs:boolean" use="required"/>
            <xs:attribute name="maxElementsInMemory" type="xs:integer" use="required"/>
            <xs:attribute name="memoryStoreEvictionPolicy" type="xs:string"/>
            <xs:attribute name="clearOnFlush" type="xs:boolean"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="overflowToDisk" type="xs:boolean" use="required"/>
            <xs:attribute name="timeToIdleSeconds" type="xs:integer"/>
            <xs:attribute name="timeToLiveSeconds" type="xs:integer"/>
            <xs:attribute name="maxElementsOnDisk" type="xs:integer"/>
            <xs:attribute name="transactionalMode" type="transactionalMode" default="off" />
            <xs:attribute name="statistics" type="xs:boolean" default="false"/>
            <xs:attribute name="copyOnRead" type="xs:boolean" default="false"/>
            <xs:attribute name="copyOnWrite" type="xs:boolean" default="false"/>
            <xs:attribute name="logging" type="xs:boolean" default="false"/>
            <xs:attribute name="cacheLoaderTimeoutMillis" type="xs:integer" default="0"/>
            <xs:attribute name="overflowToOffHeap" type="xs:boolean" default="false"/>
            <xs:attribute name="maxMemoryOffHeap" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cacheEventListenerFactory">
        <xs:complexType>
            <xs:attribute name="class" use="required"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
            <xs:attribute name="listenFor" type="notificationScope" default="all"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="bootstrapCacheLoaderFactory">
        <xs:complexType>
            <xs:attribute name="class" use="required"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cacheExtensionFactory">
        <xs:complexType>
            <xs:attribute name="class" use="required"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cacheExceptionHandlerFactory">
        <xs:complexType>
            <xs:attribute name="class" use="required"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cacheLoaderFactory">
        <xs:complexType>
            <xs:attribute name="class" use="required"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cacheDecoratorFactory">
        <xs:complexType>
            <xs:attribute name="class" use="required"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="searchAttribute">
        <xs:complexType>
            <xs:attribute name="name" use="required" type="xs:string"/>
            <xs:attribute name="expression" type="xs:string"/>
            <xs:attribute name="class" type="xs:string"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="searchable">
      <xs:complexType>
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="searchAttribute"/>
        </xs:sequence>
        <xs:attribute name="keys" type="xs:boolean" default="true"/>
        <xs:attribute name="values" type="xs:boolean" default="true"/>
      </xs:complexType>
    </xs:element>

    <xs:element name="terracotta">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="nonstop"/>
            </xs:sequence>
            <xs:attribute name="clustered" type="xs:boolean" default="true"/>
            <xs:attribute name="valueMode" type="terracottaCacheValueType" default="serialization"/>
            <xs:attribute name="coherentReads" type="xs:boolean" default="true"/>
            <xs:attribute name="localKeyCache" type="xs:boolean" default="false"/>
            <xs:attribute name="localKeyCacheSize" type="xs:positiveInteger" default="300000"/>
            <xs:attribute name="orphanEviction" type="xs:boolean" default="true"/>
            <xs:attribute name="orphanEvictionPeriod" type="xs:positiveInteger" default="4"/>
            <xs:attribute name="copyOnRead" type="xs:boolean" default="false"/>
            <xs:attribute name="coherent" type="xs:boolean" default="false"/>
            <xs:attribute name="consistency" type="consistencyType" default="strong"/>
            <xs:attribute name="synchronousWrites" type="xs:boolean" default="false"/>
            <xs:attribute name="storageStrategy" type="storageStrategyType" default="classic"/>
            <xs:attribute name="concurrency" type="xs:nonNegativeInteger" default="0"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="consistencyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="strong" />
            <xs:enumeration value="eventual" />
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="nonstop">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="timeoutBehavior"/>
            </xs:sequence>
            <xs:attribute name="enabled" type="xs:boolean" default="true"/>
            <xs:attribute name="immediateTimeout" type="xs:boolean" default="false"/>
            <xs:attribute name="timeoutMillis" type="xs:positiveInteger" default="30000"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="timeoutBehavior">
        <xs:complexType>
            <xs:attribute name="type" type="timeoutBehaviorType" default="exception"/>
            <xs:attribute name="properties" default=""/>
            <xs:attribute name="propertySeparator" default=","/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="timeoutBehaviorType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="noop" />
            <xs:enumeration value="exception" />
            <xs:enumeration value="localReads" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="monitoringType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="autodetect"/>
            <xs:enumeration value="on"/>
            <xs:enumeration value="off"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="terracottaCacheValueType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="serialization" />
            <xs:enumeration value="identity" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="storageStrategyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="classic" />
            <xs:enumeration value="DCV2" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="transactionalMode">
        <xs:restriction base="xs:string">
            <xs:enumeration value="off"/>
            <xs:enumeration value="xa_strict"/>
            <xs:enumeration value="xa"/>
            <xs:enumeration value="local"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="cacheWriter">
        <xs:complexType>
            <xs:sequence >
                <xs:element minOccurs="0" ref="cacheWriterFactory"/>
            </xs:sequence>
            <xs:attribute name="writeMode" type="writeModeType" default="write-through"/>
            <xs:attribute name="notifyListenersOnException" type="xs:boolean" default="false"/>
            <xs:attribute name="minWriteDelay" type="xs:nonNegativeInteger" default="1"/>
            <xs:attribute name="maxWriteDelay" type="xs:nonNegativeInteger" default="1"/>
            <xs:attribute name="rateLimitPerSecond" type="xs:nonNegativeInteger" default="0"/>
            <xs:attribute name="writeCoalescing" type="xs:boolean" default="false"/>
            <xs:attribute name="writeBatching" type="xs:boolean" default="false"/>
            <xs:attribute name="writeBatchSize" type="xs:positiveInteger" default="1"/>
            <xs:attribute name="retryAttempts" type="xs:nonNegativeInteger" default="0"/>
            <xs:attribute name="retryAttemptDelaySeconds" type="xs:nonNegativeInteger" default="1"/>
            <xs:attribute name="writeBehindConcurrency" type="xs:nonNegativeInteger" default="1"/>
            <xs:attribute name="writeBehindMaxQueueSize" type="xs:nonNegativeInteger" default="0"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="writeModeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="write-through" />
            <xs:enumeration value="write-behind" />
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="cacheWriterFactory">
        <xs:complexType>
            <xs:attribute name="class" use="required"/>
            <xs:attribute name="properties"/>
            <xs:attribute name="propertySeparator"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="copyStrategy">
        <xs:complexType>
            <xs:attribute name="class" use="required" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:element name="elementValueComparator">
        <xs:complexType>
            <xs:attribute name="class" use="required" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="notificationScope">
        <xs:restriction base="xs:string">
            <xs:enumeration value="local"/>
            <xs:enumeration value="remote"/>
            <xs:enumeration value="all"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== PavlidisLab/Gemma/gemma-core/src/main/resources/ehcache.xml
<?xml version="1.0" encoding="UTF-8"?>
<ehcache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://ehcache.org/ehcache.xsd">

    <!-- File for use in non-clustered environments (no terracotta) -->


    <!-- Sets the path to the directory where cache .data files are created. If the path is a Java System Property it is replaced
        by its value in the running VM. The following properties are translated: user.home - User's home directory user.dir - User's
        current working directory java.io.tmpdir - Default temp file path -->
    <diskStore path="ehcache.disk.store.dir"/>

    <!-- Customize caches below. Increase or decrease maxElementsInMemory; 10000 genes takes about 10 MB in RAM. Make items
        that are essentially immutable 'eternal'. -->

    <!-- see http://ehcache.sourceforge.net/documentation/configuration.html -->

    <!-- Hibernate -->

    <cache name="org.hibernate.cache.internal.StandardQueryCache" maxElementsInMemory="5000" timeToLiveSeconds="1200"
           timeToIdleSeconds="1200" overflowToDisk="false"/>

    <cache name="org.hibernate.cache.spi.UpdateTimestampsCache" maxElementsInMemory="5000"
           eternal="true" overflowToDisk="false"/>

    <!-- cache names must match the class element names defined in the hbm.xml files. -->

    <!-- gsec -->

    <cache name="gemma.gsec.acl.domain.AclSid"
           maxElementsInMemory="100" eternal="true" overflowToDisk="false"/>
    <cache name="gemma.gsec.acl.domain.AclObjectIdentity"
           maxElementsInMemory="10000" timeToLiveSeconds="1200" overflowToDisk="false"/>
    <cache name="gemma.gsec.acl.domain.AclObjectIdentity.entries"
           maxElementsInMemory="10000" timeToLiveSeconds="1200" overflowToDisk="false"/>
    <cache name="gemma.gsec.acl.domain.AclEntry"
           maxElementsInMemory="100000" timeToLiveSeconds="1200" overflowToDisk="false"/>

    <!-- Gemma -->

    <cache name="ubic.gemma.model.analysis.expression.diff.HitListSize"
           maxElementsInMemory="100000" eternal="true" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.sequenceAnalysis.BlatResult"
           maxElementsInMemory="100000" eternal="true" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.sequenceAnalysis.SequenceSimilaritySearchResult"
           maxElementsInMemory="100000" eternal="true" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.sequenceAnalysis.BlatAssociation" maxElementsInMemory="100000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.biosequence.BioSequence" maxElementsInMemory="200000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.biosequence.BioSequence.bioSequence2GeneProduct"
           maxElementsInMemory="10000" timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.gene.GeneAlias" maxElementsInMemory="50000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.gene.GeneProduct" maxElementsInMemory="50000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.gene.GeneProduct.accessions" maxElementsInMemory="50000" eternal="true"
           overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.gene.GeneProduct.exons" maxElementsInMemory="50000" eternal="true"
           overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.gene.GeneSetMember" maxElementsInMemory="50000" timeToLiveSeconds="1200"
           overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.gene.GeneSet" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.gene.GeneSet.characteristics" maxElementsInMemory="1000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.gene.GeneSet.members" maxElementsInMemory="1000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.gene.Multifunctionality" maxElementsInMemory="50000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.PhysicalLocation" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.ChromosomeFeature" maxElementsInMemory="200000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.Chromosome" maxElementsInMemory="1200" eternal="true" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.Taxon" maxElementsInMemory="100"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.Gene" maxElementsInMemory="50000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.Gene.products" maxElementsInMemory="50000" eternal="true"
           overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.Gene.aliases" maxElementsInMemory="50000" eternal="true"
           overflowToDisk="false"/>

    <cache name="ubic.gemma.model.genome.Gene.accessions" maxElementsInMemory="200000" eternal="true"
           overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.DatabaseEntry" maxElementsInMemory="200000"
           eternal="true" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.ExternalDatabase" maxElementsInMemory="100"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.LocalFile" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.BibliographicReference" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.BibliographicReference.annotations" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.BibliographicReference.meshTerms" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.BibliographicReference.keywords" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.BibliographicReference.chemicals" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.Characteristic" maxElementsInMemory="200000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.MedicalSubjectHeading" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.MedicalSubjectHeading.qualifiers" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.BibRefAnnotation" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.description.Keyword" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.auditAndSecurity.Person" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.auditAndSecurity.UserGroup" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.auditAndSecurity.UserGroup.notedReferenceLists" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.auditAndSecurity.UserGroup.authorities" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.auditAndSecurity.Contact" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.auditAndSecurity.User" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.auditAndSecurity.User.referenceLists" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.auditAndSecurity.User.jobs" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.auditAndSecurity.GroupAuthority" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.auditAndSecurity.JobInfo" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <!-- audit events and their types are immutables, so the cache can be eternal -->
    <cache name="ubic.gemma.model.common.auditAndSecurity.AuditEvent" maxElementsInMemory="10000"
           eternal="true" overflowToDisk="false"/>
    <cache name="ubic.gemma.model.common.auditAndSecurity.eventType.AuditEventType" maxElementsInMemory="10000"
           eternal="true" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.auditAndSecurity.curation.CurationDetails" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.measurement.Measurement" maxElementsInMemory="10000"
           timeToLiveSeconds="1200" overflowToDisk="false"/>

    <cache name="ubic.gemma.model.common.measurement.Unit" maxElementsInMemory="10000"
